#!/usr/bin/env python3
"""Generate the live-pull workflow's cron triggers from fixtures.json.

GitHub Actions drops most triggers from a high-frequency cron like
"*/15 * * * *" (observed: ~25% actually fire). Low-frequency, off-peak
crons fire far more reliably, so instead of polling blindly we place a
couple of dedicated triggers shortly before each kickoff. Once any of
them fires, live_pull.py stays alive (--max-wait) through the match and
covers every other live game in the same window, so clustered matches
only need one trigger between them to land.

Triggers are by time-of-day (deduped across the tournament), not by
date: the set of kickoff slots is small, and a trigger that fires on a
day with no match just makes two API calls and exits in seconds. This
keeps the workflow short and robust to a slightly stale fixtures.json.

Run after regenerating fixtures.json (e.g. once knockout pairings are
known) and commit the updated workflow:

    python build_fixtures.py && python build_schedule.py
"""

import json
from pathlib import Path

HERE = Path(__file__).parent
FIXTURES = HERE / "fixtures.json"
WORKFLOW = HERE / ".github" / "workflows" / "live-pull.yml"

# Minutes before kickoff to fire a trigger. Two staggered, off-peak
# attempts per slot stack the odds that at least one lands; live_pull's
# --max-wait then bridges from the trigger to the actual kickoff.
OFFSETS_MIN = (20, 5)

# A floor under the fixture-derived slots, covering the hours European club
# football is actually played (UTC).
#
# The slots above come from fixtures.json, which is the static WORLD CUP
# calendar -- an evening tournament. So the generated schedule woke at
# 15:00-16:00 and 18:00-03:00 UTC and nowhere else, and a Premier League
# Saturday (11:30 and 14:00 UTC kickoffs) had no trigger at all. Correct code
# watching nothing is still nothing watched.
#
# Deliberately a fixed band rather than a second feed to read: the real fixture
# list for an API competition lives in Supabase, and making a schedule
# generator reach into the database to decide when to wake is a lot of
# machinery to save a handful of cron lines that cost seconds each when
# nothing is on.
BASELINE_SLOTS = tuple(
    (h, m) for h in range(11, 24) for m in (10, 25, 40, 55)
)

TEMPLATE = """\
name: Live stats pull

# Watchdog. GENERATED by build_schedule.py — edit that script, not the cron
# list below — from the static World Cup calendar in fixtures.json PLUS a
# fixed baseline covering the hours European club football is played. The
# baseline is why this list is long: fixtures.json is an evening tournament,
# so on its own it left a Premier League Saturday afternoon unwatched.
# Each run exits in seconds when nothing is live or imminent;
# otherwise live_pull.py stays alive (--max-wait), polling every 5 minutes
# until the day's matches end. The concurrency group stops triggers from
# stacking while a loop is running. The daily + same-day catch-up sweeps
# remain the authoritative reconciliation.
on:
  schedule:
{cron_lines}
  workflow_dispatch:

concurrency:
  group: live-pull
  cancel-in-progress: false

jobs:
  live:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Watch / pull live stats
        env:
          API_FOOTBALL_KEY: ${{{{ secrets.API_FOOTBALL_KEY }}}}
          SUPABASE_URL: ${{{{ secrets.SUPABASE_URL }}}}
          SUPABASE_SERVICE_KEY: ${{{{ secrets.SUPABASE_SERVICE_KEY }}}}
          FANTASY_LEAGUE_ID: ${{{{ secrets.FANTASY_LEAGUE_ID }}}}
        run: python live_pull.py
"""


def trigger_times(fixtures: list) -> list:
    """Distinct (hour, minute) UTC trigger times across all kickoffs."""
    slots = set()
    for f in fixtures:
        iso = f.get("kickoff_utc", "")
        if len(iso) < 16:
            continue
        hh, mm = int(iso[11:13]), int(iso[14:16])
        for off in OFFSETS_MIN:
            t = (hh * 60 + mm - off) % (24 * 60)
            slots.add((t // 60, t % 60))
    return sorted(slots)


def main() -> None:
    fixtures = json.loads(FIXTURES.read_text(encoding="utf-8"))
    times = sorted(set(trigger_times(fixtures)) | set(BASELINE_SLOTS))
    if not times:
        raise SystemExit("No kickoff times to schedule.")
    cron_lines = "\n".join(
        f'    - cron: "{m} {h} * * *"' for h, m in times
    )
    WORKFLOW.write_text(TEMPLATE.format(cron_lines=cron_lines), encoding="utf-8")
    print(f"Wrote {len(times)} trigger(s) to {WORKFLOW.relative_to(HERE)} "
          f"from {len(fixtures)} fixtures plus the club-football baseline.")


if __name__ == "__main__":
    main()
