/* Assemble the deployable site into public/.
 *
 * Cloudflare Pages publishes one directory, so we copy exactly the files the
 * app needs at runtime rather than serving the whole repo. That keeps
 * schema.sql, rls.sql, the Python pull scripts and node_modules off the public
 * internet, and makes "what is actually deployed" a list you can read.
 *
 * Run via `npm run build` (which also compiles the CSS and refreshes the
 * vendored Supabase client first).
 */
const fs = require("fs");
const path = require("path");

const OUT = "public";
// sim.js ships, but its controls only render for an APP_OWNER_EMAILS account
// and every write it makes is refused unless the league is flagged `sim`. The
// gate below fails the build if either of those protections goes missing.
const DEV = process.env.BUILD_ENV === "dev";

// Missing a required file should fail the build loudly; the optional data files
// are generated by the scheduled pull workflows and may legitimately be absent.
const REQUIRED = [
  "index.html",
  "theme.js",
  "app.js",
  "styles.css",
  "_headers",
  "vendor/supabase.js",
  "players.json",
];
/* sticker.html is a TEMPORARY design preview, not part of the app -- nothing
   links to it and it links to nothing. It is served from this domain only
   because the artifact sandbox blocks every external host, so it is the one
   place the redesign can be seen with the real player photos and club crests
   (which _headers already allows from media.api-sports.io). Delete this entry
   and the file once a direction is chosen. */
const OPTIONAL = ["fixtures.json", "photos.json", "injuries.json", "sticker.html"];

/* styles.css is GENERATED from the classes used in index.html, app.js and
   sim.js — so adding a utility class and running only this script copies a
   stylesheet that does not contain it. The page then renders with the class
   silently doing nothing, which is how a sort control lost its width and a
   heading went back to wrapping, on a build whose local screenshots looked
   fine because a <select> happens to size itself to its longest option.

   CI catches it, but a check that only fires after a push is a slow way to
   learn. This fails here instead, before anything is deployed. Skipped when
   the CSS toolchain is absent, so a fresh clone without node_modules can
   still assemble the site. */
function assertCssFresh() {
  const { execFileSync } = require("child_process");
  const tw = path.join("node_modules", ".bin", "tailwindcss");
  if (!fs.existsSync(tw) || !fs.existsSync("src.css")) return;
  const before = fs.readFileSync("styles.css", "utf8");
  const tmp = path.join(require("os").tmpdir(), `styles-check-${process.pid}.css`);
  try {
    execFileSync(tw, ["-i", "src.css", "-o", tmp, "--minify"], { stdio: "ignore" });
    if (fs.readFileSync(tmp, "utf8") !== before) {
      console.error("styles.css is out of date — run `npm run build:css` and commit it.");
      console.error("(a class you used is not in the stylesheet, so it will do nothing)");
      process.exit(1);
    }
  } catch (e) {
    if (e && e.status === 1 && !e.stdout) throw e;   // our own exit, not a tool failure
  } finally {
    try { fs.unlinkSync(tmp); } catch { /* nothing to clean up */ }
  }
}

assertCssFresh();

fs.rmSync(OUT, { recursive: true, force: true });

let copied = 0;
const missing = [];
for (const rel of [...REQUIRED, ...OPTIONAL]) {
  if (!fs.existsSync(rel)) {
    if (REQUIRED.includes(rel)) missing.push(rel);
    else console.warn(`  (skipped optional ${rel} — not generated yet)`);
    continue;
  }
  const dest = path.join(OUT, rel);
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.copyFileSync(rel, dest);
  copied++;
}

if (missing.length) {
  console.error(`\nBuild failed — required file(s) missing: ${missing.join(", ")}`);
  process.exit(1);
}

// A stray inline <script> or external asset would silently defeat the CSP in
// _headers, so fail here rather than in a user's browser.
let html = fs.readFileSync("index.html", "utf8");
html = html.replace("<!--SIM-->", '<script src="sim.js"></script>');
fs.copyFileSync("sim.js", path.join(OUT, "sim.js"));
copied++;
fs.writeFileSync(path.join(OUT, "index.html"), html);
const external = html.match(/<(?:script|link)[^>]+(?:src|href)="https?:\/\/[^"]*"/g);
if (external) {
  console.error("\nBuild failed — index.html loads external assets:\n  " + external.join("\n  "));
  process.exit(1);
}
if (/<script>(?![\s]*<\/script>)/.test(html.replace(/<script src="[^"]*"><\/script>/g, ""))) {
  console.error("\nBuild failed — index.html contains an inline <script>; CSP forbids it.");
  process.exit(1);
}

/* The test-run tool writes invented results, so its two protections are load
   bearing: the panel is owner-only, and no write proceeds unless the league is
   a sandbox. Deleting either would silently arm a fake-results button for every
   user, which no test would catch — so assert them at build time. */
const simSrc = fs.readFileSync("sim.js", "utf8");
const simGuards = [
  // Bounded by [^}] so a check cannot be "found" inside a DIFFERENT function
  // after the real one is deleted — that would make these assertions useless.
  [/function simSafe\(\)\s*\{[^}]*?if \(!simLeague\(\)\)/, "simSafe() no longer requires a sandbox league"],
  [/function renderTestTab\(\)\s*\{[^}]*?isAppOwner\(\)/, "the test tab no longer checks isAppOwner()"],
  [/async function simEnable\([^)]*\)\s*\{[^}]*?if \(!isAppOwner\(\)\) return/, "simEnable() no longer checks isAppOwner()"],
];
for (const [re, why] of simGuards) {
  if (!re.test(simSrc)) {
    console.error(`\nBuild failed — ${why}. sim.js writes invented results; it must stay gated.`);
    process.exit(1);
  }
}
const appSrc = fs.readFileSync("app.js", "utf8");
if (!/const statsScope = \(\) => \{[\s\S]*?!simLeague\(\)/.test(appSrc)) {
  console.error("\nBuild failed — statsScope() no longer routes a sandbox league away from"
    + " competition_stats; invented results would reach every league on the competition.");
  process.exit(1);
}
console.log(`Built ${OUT}/ — ${copied + (DEV ? 1 : 0)} files, same-origin only${DEV ? " (DEV)" : ""}.`);
