/* Assemble the deployable site into public/.
 *
 * Cloudflare Pages publishes one directory, so we copy exactly the files the
 * app needs at runtime rather than serving the whole repo. That keeps
 * schema.sql, rls.sql, the Python pull scripts and node_modules off the public
 * internet, and makes "what is actually deployed" a list you can read.
 *
 * Run via `npm run build` (which also compiles the CSS and refreshes the
 * vendored Supabase client first).
 */
const fs = require("fs");
const path = require("path");

const OUT = "public";

// Missing a required file should fail the build loudly; the optional data files
// are generated by the scheduled pull workflows and may legitimately be absent.
const REQUIRED = [
  "index.html",
  "app.js",
  "styles.css",
  "_headers",
  "vendor/supabase.js",
  "players.json",
];
const OPTIONAL = ["fixtures.json", "photos.json", "injuries.json"];

fs.rmSync(OUT, { recursive: true, force: true });

let copied = 0;
const missing = [];
for (const rel of [...REQUIRED, ...OPTIONAL]) {
  if (!fs.existsSync(rel)) {
    if (REQUIRED.includes(rel)) missing.push(rel);
    else console.warn(`  (skipped optional ${rel} — not generated yet)`);
    continue;
  }
  const dest = path.join(OUT, rel);
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.copyFileSync(rel, dest);
  copied++;
}

if (missing.length) {
  console.error(`\nBuild failed — required file(s) missing: ${missing.join(", ")}`);
  process.exit(1);
}

// A stray inline <script> or external asset would silently defeat the CSP in
// _headers, so fail here rather than in a user's browser.
const html = fs.readFileSync("index.html", "utf8");
const external = html.match(/<(?:script|link)[^>]+(?:src|href)="https?:\/\/[^"]*"/g);
if (external) {
  console.error("\nBuild failed — index.html loads external assets:\n  " + external.join("\n  "));
  process.exit(1);
}
if (/<script>(?![\s]*<\/script>)/.test(html.replace(/<script src="[^"]*"><\/script>/g, ""))) {
  console.error("\nBuild failed — index.html contains an inline <script>; CSP forbids it.");
  process.exit(1);
}

console.log(`Built ${OUT}/ — ${copied} files, same-origin only.`);
