#!/usr/bin/env python3
"""Generate the live-pull workflow's cron triggers from fixtures.json.

GitHub Actions drops most triggers from a high-frequency cron like
"*/15 * * * *" (observed: ~25% actually fire). Low-frequency, off-peak
crons fire far more reliably, so instead of polling blindly we place a
couple of dedicated triggers shortly before each kickoff. Once any of
them fires, live_pull.py stays alive (--max-wait) through the match and
covers every other live game in the same window, so clustered matches
only need one trigger between them to land.

Triggers are by time-of-day (deduped across the tournament), not by
date: the set of kickoff slots is small, and a trigger that fires on a
day with no match just makes two API calls and exits in seconds. This
keeps the workflow short and robust to a slightly stale fixtures.json.

Run after regenerating fixtures.json (e.g. once knockout pairings are
known) and commit the updated workflow:

    python build_fixtures.py && python build_schedule.py
"""

import json
from pathlib import Path

HERE = Path(__file__).parent
FIXTURES = HERE / "fixtures.json"
WORKFLOW = HERE / ".github" / "workflows" / "live-pull.yml"

# Minutes before kickoff to fire a trigger. Two staggered, off-peak
# attempts per slot stack the odds that at least one lands; live_pull's
# --max-wait then bridges from the trigger to the actual kickoff.
OFFSETS_MIN = (20, 5)

TEMPLATE = """\
name: Live stats pull

# Watchdog triggered shortly before each kickoff. GENERATED by
# build_schedule.py from fixtures.json — edit that script, not the cron
# list below. Each run exits in seconds when nothing is live or imminent;
# otherwise live_pull.py stays alive (--max-wait), polling every 5 minutes
# until the day's matches end. The concurrency group stops triggers from
# stacking while a loop is running. The daily + same-day catch-up sweeps
# remain the authoritative reconciliation.
on:
  schedule:
{cron_lines}
  workflow_dispatch:

concurrency:
  group: live-pull
  cancel-in-progress: false

jobs:
  live:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Watch / pull live stats
        env:
          API_FOOTBALL_KEY: ${{{{ secrets.API_FOOTBALL_KEY }}}}
          SUPABASE_URL: ${{{{ secrets.SUPABASE_URL }}}}
          SUPABASE_SERVICE_KEY: ${{{{ secrets.SUPABASE_SERVICE_KEY }}}}
          FANTASY_LEAGUE_ID: ${{{{ secrets.FANTASY_LEAGUE_ID }}}}
        run: python live_pull.py
"""


def trigger_times(fixtures: list) -> list:
    """Distinct (hour, minute) UTC trigger times across all kickoffs."""
    slots = set()
    for f in fixtures:
        iso = f.get("kickoff_utc", "")
        if len(iso) < 16:
            continue
        hh, mm = int(iso[11:13]), int(iso[14:16])
        for off in OFFSETS_MIN:
            t = (hh * 60 + mm - off) % (24 * 60)
            slots.add((t // 60, t % 60))
    return sorted(slots)


def main() -> None:
    fixtures = json.loads(FIXTURES.read_text(encoding="utf-8"))
    times = trigger_times(fixtures)
    if not times:
        raise SystemExit("No kickoff times in fixtures.json — nothing to schedule.")
    cron_lines = "\n".join(
        f'    - cron: "{m} {h} * * *"' for h, m in times
    )
    WORKFLOW.write_text(TEMPLATE.format(cron_lines=cron_lines), encoding="utf-8")
    print(f"Wrote {len(times)} trigger(s) to {WORKFLOW.relative_to(HERE)} "
          f"from {len(fixtures)} fixtures.")


if __name__ == "__main__":
    main()
