const { test, expect } = require("@playwright/test");

/* Does the deployed site actually start?
 *
 * The unit suite loads app.js into a stub DOM and asserts hard about its
 * logic, which is why it can be 700 assertions deep and still miss:
 *   - a script that 404s (build.js copies a file list; a rename slips through)
 *   - a CSP in _headers that blocks something the app needs
 *   - a reference error on the boot path, which `new Function(src)` never runs
 *   - CSS that never loaded, so the app renders as unstyled markup
 * All of those are invisible until someone opens the page. This opens it.
 *
 * No Supabase: with none configured the app must reach its own first-run
 * state rather than throwing. That is worth asserting on its own -- it is
 * what a brand new visitor gets.
 */

// Errors the page reports about itself. Collected per test rather than
// globally so a failure names the test that provoked it.
function watch(page) {
  const errors = [];
  page.on("pageerror", (e) => errors.push(`uncaught: ${e.message}`));
  page.on("console", (m) => {
    /* "Failed to load resource" is the browser narrating a failed request; the
       request listeners below name the URL, which is the part worth reading.
       Keeping both means every 404 is reported twice, once uselessly. */
    if (m.type() === "error" && !/Failed to load resource/.test(m.text()))
      errors.push(`console.error: ${m.text()}`);
  });
  page.on("requestfailed", (r) =>
    errors.push(`failed request: ${r.url()} (${r.failure()?.errorText})`));
  // A favicon the site does not ship is the browser asking, not the app
  // failing; everything else that 404s is a real missing asset.
  page.on("response", (r) => {
    if (r.status() >= 400 && !/favicon/.test(r.url()))
      errors.push(`${r.status()} ${r.url()}`);
  });
  return errors;
}

test("the app boots with no uncaught errors", async ({ page }) => {
  const errors = watch(page);
  const responses = [];
  page.on("response", (r) => responses.push([r.url(), r.status()]));

  await page.goto("/index.html", { waitUntil: "networkidle" });

  // Every asset the page asked for arrived. A 404 here means build.js copied
  // a list that no longer matches what index.html references.
  const missing = responses.filter(([u, s]) => s >= 400 && !/favicon/.test(u));
  expect(missing, `assets failed to load: ${JSON.stringify(missing)}`).toEqual([]);
  expect(errors, errors.join("\n")).toEqual([]);
});

test("the stylesheet is applied, not merely served", async ({ page }) => {
  await page.goto("/index.html", { waitUntil: "networkidle" });
  /* styles.css 200ing proves nothing -- it is generated by Tailwind from a
     content list, and a file missing from that list gets its classes purged
     while the request still succeeds. That is not hypothetical: sim.js was
     missing from the globs and five of its classes had no rules at all.
     So assert a rule actually took effect. */
  const bodyBg = await page.evaluate(() =>
    getComputedStyle(document.body).backgroundColor);
  expect(bodyBg, "body has no background — styles.css did not apply").not.toBe("rgba(0, 0, 0, 0)");
});

test("app.js defined its globals", async ({ page }) => {
  await page.goto("/index.html", { waitUntil: "networkidle" });
  // If app.js threw partway through, these are missing while the page still
  // looks broadly fine — the failure mode that motivated this file.
  /* `typeof S`, not `window.S`: app.js declares its state with const, and
     const/let at script top level create global BINDINGS without becoming
     properties of window. Asserting on window.S would fail against a perfectly
     healthy page — a wrong test, not a wrong app. */
  const present = await page.evaluate(() => ({
    state: typeof S,
    scoring: typeof computeScores,
    settle: typeof advanceRound,
  }));
  expect(present).toEqual({ state: "object", scoring: "function", settle: "function" });
});

test("the draft clock never renders NaN", async ({ page }) => {
  /* Date.parse(null) is NaN, and Math.max(0, NaN) is NaN too — so the clamp
     that looked like it guarded this did nothing, and a league whose pick had
     not been started yet showed "NaN:NaN" in display type on the most public
     screen in the app. */
  await page.goto("/index.html", { waitUntil: "networkidle" });
  const shown = await page.evaluate(() => {
    S.league = { id: "L", current_pick: 1, pick_duration_seconds: 60,
                 num_managers: 2, config: {} };
    S.managers = [{ id: "m1", draft_position: 1, name: "A" },
                  { id: "m2", draft_position: 2, name: "B" }];
    S.picks = [];
    const out = {};
    for (const started of [null, undefined, "", "not-a-date"]) {
      S.league.pick_started_at = started;
      tickTimer();
      out[String(started)] = document.getElementById("draft-clock").textContent;
    }
    // ...and a real timestamp still counts down, so the guard did not swallow
    // the working case.
    S.league.pick_started_at = new Date(Date.now() - 10000).toISOString();
    tickTimer();
    out.real = document.getElementById("draft-clock").textContent;
    return out;
  });
  for (const [k, v] of Object.entries(shown)) {
    if (k === "real") continue;
    expect(v, `pick_started_at=${k} rendered "${v}"`).not.toMatch(/NaN/);
  }
  expect(shown.real, "a started pick no longer shows a countdown").toMatch(/^\d+:\d\d$/);
});
